name: Compile all binaries

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-amd64:
    runs-on: ubuntu-22.04

    steps:
    - name: Setup APT
      run: |
        echo 'APT::Acquire::Retries "4";' | sudo tee /etc/apt/apt.conf.d/80-retries
        export PKG_CONFIG_PATH="/usr/lib/pkgconfig:$PATH"
        export DEBIAN_FRONTEND="noninteractive"
        sudo apt update -y
        sudo apt install -y git make cmake ninja-build gcc g++ appstream pkg-config plasma-workspace-dev qttools5-dev libqt5svg5-dev libkf5networkmanagerqt-dev extra-cmake-modules

    - uses: actions/checkout@v2
      with:
        ref: 'master'
        submodules: 'recursive'

    - uses: actions/checkout@v2
      with:
        repository: Martchus/cpp-utilities
        ref: 'master'
        submodules: 'recursive'
        path: './cpp-utilities'

    - name: Compile cpp-utilities
      run: |
        cd cpp-utilities
        cmake \
          -G Ninja \
          -DCMAKE_BUILD_TYPE:STRING='Release' \
          -DCMAKE_INSTALL_PREFIX:PATH='/usr' \
          -DBUILD_SHARED_LIBS:BOOL=OFF \
          .
        ninja
        sudo ninja install
        
    - uses: actions/checkout@v2
      with:
        repository: Martchus/qtutilities
        ref: 'master'
        submodules: 'recursive'
        path: './qtutilities'
        
    - name: Compile qtutilities
      run: |
        cd qtutilities
        cmake \
          -G Ninja \
          -DCMAKE_BUILD_TYPE:STRING='Release' \
          -DCMAKE_INSTALL_PREFIX:PATH='/usr' \
          -DBUILD_SHARED_LIBS:BOOL=OFF \
          -DBUILTIN_TRANSLATIONS:BOOL=ON \
          .
        ninja
        sudo ninja install

    - name: Initialize project
      run: |
        git config --global --add safe.directory '*'
        mkdir build && cd build
        mkdir deploy
        cmake .. -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/deploy

    - name: Build
      run: |
        cd build
        make install

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact-amd64
        path: build/deploy/
